### PR TITLE
feat: Update Smartfren

### PR DESCRIPTION
**Pull request by reinhart1010**

### CODE REVIEW

**Comment by SlashyID** [comment]
Memang https://1.1.1.1 atau https://1.0.0.1 gak bisa diakses melalui jaringan smartfren?

**Comment by MeFinity** [comment]
Halo? Jika anda tidak memverifikasikan informasi ini PRnya tidak akan di merge

**Comment by reinhart1010** [comment]
Oke sebentar

**Comment by reinhart1010** [comment]
I've tested with an external Wi-Fi GSM router and the Cloudflare endpoint seems to be unblocked (using the raw IP address). Closing this as invalid.

image

**Note:** All `traceroute` results always return `* * *` even for whitelisted sites.

**Pull request closed without merging**
